[package]
name    = "libkql"
version = "0.0.3"
authors = ["kalmari"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
failure         = "0.1.6"
goblin          = "0.0.24"
libc            = "0.2.65"
null-terminated = "0.3.9"
which           = "3.0.0"

[profile.release]
lto = true
